/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface VtcSkeleton {
    /**
    * Enables or disables animation of the skeleton element
    */
    'animated': boolean;
    /**
    * The height of the skeleton element
    */
    'height': string;
    /**
    * The width of the skeleton element
    */
    'width': string;
  }
  interface VtcSkeletonAttributes extends StencilHTMLAttributes {
    /**
    * Enables or disables animation of the skeleton element
    */
    'animated'?: boolean;
    /**
    * The height of the skeleton element
    */
    'height'?: string;
    /**
    * The width of the skeleton element
    */
    'width'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'VtcSkeleton': Components.VtcSkeleton;
  }

  interface StencilIntrinsicElements {
    'vtc-skeleton': Components.VtcSkeletonAttributes;
  }


  interface HTMLVtcSkeletonElement extends Components.VtcSkeleton, HTMLStencilElement {}
  var HTMLVtcSkeletonElement: {
    prototype: HTMLVtcSkeletonElement;
    new (): HTMLVtcSkeletonElement;
  };

  interface HTMLElementTagNameMap {
    'vtc-skeleton': HTMLVtcSkeletonElement
  }

  interface ElementTagNameMap {
    'vtc-skeleton': HTMLVtcSkeletonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
